server:
  port: 8000
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  thumbImage:
    height: 150
    width: 150
  tracker-list: 192.168.16.82:22122             #192.168.29.131:22122
  web-server-url: http://192.168.16.82:18888/
spring:
  profiles:
    active: druid,oracle,thyeleaf
