server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/gongxusheng/spring-config-demo.git
          searchPaths: my-sample-config
#           uri: https://github.com/yuyumimi/springcloudtest.git
#           searchPaths: cloud-config