server:
  port: 9999
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）生产环境最好使用默认值
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
    healthcheck:
      enabled: true                           # 开启健康检查（依赖spring-boot-starter-actuator）
spring:
  application:
      name: service-config    # 对应config server所获取的配置文件的{application}
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  cloud:
    bus:
      trace:
        enabled: true
  profiles:
    active: native,na                  #本地native,na

management:
  security:
    enabled: false
security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: user                  # 配置登录的账号是user
    password: password123       # 配置登录的密码是password123