spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/itmuch/spring-cloud-config-repo
#          searchPaths: my-sample-config
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
#           uri: https://github.com/yuyumimi/springcloudtest.git
#           searchPaths: cloud-config