spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    encoding: UTF-8
    cache: false
    enabled: true
    mode: HTML5
    check-template-location: true