spring:
  datasource:
    url: jdbc:oracle:thin:@172.20.65.236:1521:bjrac
    username: sior
    password: sior
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update