spring:
  freemarker:
    template-loader-path: classpath:/template
    suffix: .ftl
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request