server:
  port: 9060

spring:
  application:
    name: auth2.0-service
  zipkin:
      base-url: http://localhost:9050
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@172.20.65.236:1521:bjrac
    username: sior
    password: sior
    druid:
      driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123456
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）生产环境最好使用默认值
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

  client:
      service-url:
        defaultZone: http://user:password123@localhost:8761/eureka/
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
