server:
  port: 8761
logging:
  level:
    root: WARN
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false           # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 5000       # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  client:
    registerWithEureka: false                 # false当前不是eureka客户端（默认为客户端）
    fetchRegistry: false                      # false当前不是eureka客户端（默认为客户端）
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/